Updated deployment mechanism

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -42,18 +42,44 @@ jobs:
     steps:
       - name: validate job parameters
         run: |
-          echo """ \
-            Executing deploy job using parameters:
-              (Release Version)    - $RC_VER
-              (Target Environment) - $RC_ENV
-          """
+          get_latest_version() {
+            local bucket_name=$1
+            local prefix_path=$2
+
+            directories=$(aws s3 ls s3://$bucket_name/$prefix_path/ --summarize --human-readable | grep -E 'PRE|DIR' | awk '{print $2}')
+            latest_version=""
+            while IFS= read -r dir; do
+              version=$(basename "$dir")
+              if [[ $version =~ ^[0-9]+(\.[0-9]+){2}$ ]]; then
+                if [[ -z $latest_version ]] || (( $(echo "$version" | awk -F '.' '{print $1*10000+$2*100+$3}') > $(echo "$latest_version" | awk -F '.' '{print $1*10000+$2*100+$3}') )); then
+                  latest_version=$version
+                fi
+              fi
+            done <<< "$directories"
+            echo "$latest_version"
+          }
+
+          if [[ $RC_VER == "latest" ]]; then 
+            latest_version=$(get_latest_version $RC_SRC 'releases')
+            echo """ \
+              Executing deploy job using parameters:
+                (Release Version)    - $latest_version (latest)
+                (Target Environment) - $RC_ENV
+            """
+            echo "RC_VER=${latest_version}" >> "$GITHUB_ENV"
+          else
+            echo """ \
+              Executing deploy job using parameters:
+                (Release Version)    - $RC_VER
+                (Target Environment) - $RC_ENV
+            """
 
       - name: configure aws credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-region: ${{ env.AWS_REGION }}
           role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
-          role-session-name: ${{ env.RC_ENV }}-app-deployment
+          role-session-name: ${{ env.RC_ENV }}-app-deployment-validation
           role-duration-seconds: 3600
           role-skip-session-tagging: true
           
@@ -62,19 +88,71 @@ jobs:
           RC_SRC: ${{ env.RC_SRC_PREFIX }}-${{ vars.AWS_ACCOUNT_ID }}
         run: |
           [[ $RC_VER =~ ^[0-9]+(\.[0-9]+){2}$ ]] && rc_path="$RC_SRC/releases/$RC_VER" || rc_path="$RC_SRC/releases-dev/$RC_VER"
+
           rc_backend_path="$rc_path/backend"
           rc_frontend_path="$rc_path/frontend/$RC_ENV"
+          rc_database_path="$rc_path/sql"
 
           if [[ `aws s3 ls s3://$rc_backend_path|head` ]]; then
             if [[ `aws s3 ls s3://$rc_frontend_path|head` ]]; then
-              echo "Release candidate version [${RC_VER}] successfully validated"
+              if [[ `aws s3 ls s3://$rc_database_path|head` ]]; then
+                echo "[INFO] Release candidate version [${RC_VER}] successfully validated"
+              else
+                echo "[ERROR] Release candidate version [${RC_VER}] does not exist for component (DATABASE). Exiting"
+                exit 1
             else
-              echo "Release candidate version [${RC_VER}] does not exist for component (FRONTEND). Exiting"
+              echo "[ERROR] Release candidate version [${RC_VER}] does not exist for component (FRONTEND). Exiting"
               exit 1
             fi
           else
-            echo "Release candidate version [${RC_VER}] does not exist for component (BACKEND). Exiting"
+            echo "[ERROR] Release candidate version [${RC_VER}] does not exist for component (BACKEND). Exiting"
             exit 1
+          fi
+
+  database:
+    runs-on: ubuntu-latest
+    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment ||
+      github.event_name == 'repository_dispatch' && github.event.client_payload.environment }}
+    needs: validation
+
+    steps:
+      - name: configure aws credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: ${{ env.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
+          role-session-name: ${{ env.RC_ENV }}-database-deployment
+          role-duration-seconds: 3600
+          role-skip-session-tagging: true
+
+      - name: deploy database migrations for ${{ env.RC_ENV }}
+        env:
+          RC_SRC: ${{ env.RC_SRC_PREFIX }}-${{ vars.AWS_ACCOUNT_ID }}
+        run: |
+          [[ $RC_VER =~ ^[0-9]+(\.[0-9]+){2}$ ]] && rc_path="releases" || rc_path="releases-dev"
+          lambda_function_name="${RC_ENV}-epp-pg-mutate-lambda"
+          read -r -d '' payload << EOF
+          {
+            "type": "run_migrations",
+            "userCredentialsArn": "${RC_ENV}/epp/rds/user/epp_app_rw",
+            "targetDatabase": "epp",
+            "databaseMigrations": {
+              "bucketName": "${RC_SRC}",
+              "bucketPrefix": "${rc_path}",
+              "releaseVersion": "${RC_VER}"
+            }
+          }
+          EOF
+
+          response=$(aws lambda invoke --function-name $lambda_function_name --region ${{ env.AWS_REGION }} --payload "$payload" response.txt 2>&1)
+          if [[ "$response" == *"FunctionError"* ]]; then
+            echo "[ERROR] Deployment of application component (DATABASE) with version ${RC_VER} failed with error:"
+            echo "${response}"
+            exit 1
+          else
+            response_payload=$(cat response.txt)
+            echo "Response Payload: $response_payload"
+            echo "[INFO] Application component (DATABASE) with version ${RC_VER} successfully deployed into ${RC_ENV^^}"
           fi
 
   backend:
@@ -101,7 +179,7 @@ jobs:
         with:
           aws-region: ${{ env.AWS_REGION }}
           role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
-          role-session-name: ${{ env.RC_ENV }}-app-deployment
+          role-session-name: ${{ env.RC_ENV }}-backend-app-deployment
           role-duration-seconds: 3600
           role-skip-session-tagging: true
 
@@ -144,7 +222,7 @@ jobs:
         with:
           aws-region: ${{ env.AWS_REGION }}
           role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
-          role-session-name: ${{ env.RC_ENV }}-app-deployment
+          role-session-name: ${{ env.RC_ENV }}-frontend-app-deployment
           role-duration-seconds: 3600
           role-skip-session-tagging: true
 
