[BODS-4377] DB Migration Mechanism (#6)
Co-authored-by: Rob Steel <=>

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,7 +9,7 @@ on:
         type: string
         description: version to be deployed
         required: true
-        default: '0.0.0'
+        default: 'latest'
       environment:
         type: choice
         description: deployment environment
@@ -38,43 +38,133 @@ jobs:
     runs-on: ubuntu-latest
     environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment ||
       github.event_name == 'repository_dispatch' && github.event.client_payload.environment }}
+    outputs:
+      version: ${{ steps.verify.outputs.version }}
 
     steps:
-      - name: validate job parameters
-        run: |
-          echo """ \
-            Executing deploy job using parameters:
-              (Release Version)    - $RC_VER
-              (Target Environment) - $RC_ENV
-          """
-
       - name: configure aws credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-region: ${{ env.AWS_REGION }}
           role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
-          role-session-name: ${{ env.RC_ENV }}-app-deployment
+          role-session-name: ${{ env.RC_ENV }}-app-deployment-validation
           role-duration-seconds: 3600
           role-skip-session-tagging: true
-          
-      - name: validate release candidate version
+
+      - name: validate job parameters
+        id: verify
         env:
           RC_SRC: ${{ env.RC_SRC_PREFIX }}-${{ vars.AWS_ACCOUNT_ID }}
         run: |
-          [[ $RC_VER =~ ^[0-9]+(\.[0-9]+){2}$ ]] && rc_path="$RC_SRC/releases/$RC_VER" || rc_path="$RC_SRC/releases-dev/$RC_VER"
+          get_latest_version() {
+            local bucket_name=$1
+            local prefix_path=$2
+
+            directories=$(aws s3 ls s3://$bucket_name/$prefix_path/ --summarize --human-readable | grep -E 'PRE|DIR' | awk '{print $2}')
+            latest_version=""
+            while IFS= read -r dir; do
+              version=$(basename "$dir")
+              if [[ $version =~ ^[0-9]+(\.[0-9]+){2}$ ]]; then
+                if [[ -z $latest_version ]] || (( $(echo "$version" | awk -F '.' '{print $1*10000+$2*100+$3}') > $(echo "$latest_version" | awk -F '.' '{print $1*10000+$2*100+$3}') )); then
+                  latest_version=$version
+                fi
+              fi
+            done <<< "$directories"
+            echo "$latest_version"
+          }
+
+          if [[ $RC_VER == "latest" ]]; then 
+            latest_version=$(get_latest_version $RC_SRC 'releases')
+            echo """ \
+              Executing deploy job using parameters:
+                (Release Version)    - $latest_version (latest)
+                (Target Environment) - $RC_ENV
+            """
+            echo "version=${latest_version}" >> "$GITHUB_OUTPUT"
+          else
+            echo """ \
+              Executing deploy job using parameters:
+                (Release Version)    - $RC_VER
+                (Target Environment) - $RC_ENV
+            """
+            echo "version=${RC_VER}" >> "$GITHUB_OUTPUT"
+          fi
+
+
+      - name: validate release candidate version
+        env:
+          RC_SRC: ${{ env.RC_SRC_PREFIX }}-${{ vars.AWS_ACCOUNT_ID }}
+          VERSION: ${{ steps.verify.outputs.version }}
+        run: |
+          [[ $VERSION =~ ^[0-9]+(\.[0-9]+){2}$ ]] && rc_path="$RC_SRC/releases/$VERSION" || rc_path="$RC_SRC/releases-dev/$VERSION"
+
           rc_backend_path="$rc_path/backend"
           rc_frontend_path="$rc_path/frontend/$RC_ENV"
+          rc_database_path="$rc_path/sql"
 
           if [[ `aws s3 ls s3://$rc_backend_path|head` ]]; then
             if [[ `aws s3 ls s3://$rc_frontend_path|head` ]]; then
-              echo "Release candidate version [${RC_VER}] successfully validated"
+              if [[ `aws s3 ls s3://$rc_database_path|head` ]]; then
+                echo "[INFO] Release candidate version [${VERSION}] successfully validated"
+              else
+                echo "[ERROR] Release candidate version [${VERSION}] does not exist for component (DATABASE). Exiting"
+                exit 1
+              fi
             else
-              echo "Release candidate version [${RC_VER}] does not exist for component (FRONTEND). Exiting"
+              echo "[ERROR] Release candidate version [${VERSION}] does not exist for component (FRONTEND). Exiting"
               exit 1
             fi
           else
-            echo "Release candidate version [${RC_VER}] does not exist for component (BACKEND). Exiting"
+            echo "[ERROR] Release candidate version [${VERSION}] does not exist for component (BACKEND). Exiting"
             exit 1
+          fi
+
+  database:
+    runs-on: ubuntu-latest
+    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment ||
+      github.event_name == 'repository_dispatch' && github.event.client_payload.environment }}
+    needs: validation
+
+    steps:
+      - name: configure aws credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: ${{ env.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
+          role-session-name: ${{ env.RC_ENV }}-database-deployment
+          role-duration-seconds: 3600
+          role-skip-session-tagging: true
+
+      - name: deploy database migrations for ${{ env.RC_ENV }}
+        env:
+          RC_SRC: ${{ env.RC_SRC_PREFIX }}-${{ vars.AWS_ACCOUNT_ID }}
+          VERSION: ${{ needs.validation.outputs.version }}
+        run: |
+          [[ $VERSION =~ ^[0-9]+(\.[0-9]+){2}$ ]] && rc_path="releases" || rc_path="releases-dev"
+          lambda_function_name="${RC_ENV}-epp-pg-mutate-lambda"
+          cat <<EOF > $GITHUB_WORKSPACE/payload.json
+          {
+            "type": "run_migrations",
+            "userCredentialsArn": "${RC_ENV}/epp/rds/user/epp_app_rw",
+            "targetDatabase": "epp",
+            "databaseMigrations": {
+              "bucketName": "${RC_SRC}",
+              "bucketPrefix": "${rc_path}",
+              "releaseVersion": "${VERSION}"
+            }
+          }
+          EOF
+
+          openssl base64 -out $GITHUB_WORKSPACE/encoded_payload.json -in $GITHUB_WORKSPACE/payload.json 
+          response=$(aws lambda invoke --function-name $lambda_function_name --region $AWS_REGION --payload file://$GITHUB_WORKSPACE/encoded_payload.json response.txt 2>&1)
+          if [[ "$response" == *"FunctionError"* ]]; then
+            echo "[ERROR] Deployment of application component (DATABASE) with version ${VERSION} failed with error:"
+            echo "${response}"
+            exit 1
+          else
+            response_payload=$(cat response.txt)
+            echo "Response Payload: $response_payload"
+            echo "[INFO] Application component (DATABASE) with version ${VERSION} successfully deployed into ${RC_ENV^^}"
           fi
 
   backend:
@@ -101,19 +191,20 @@ jobs:
         with:
           aws-region: ${{ env.AWS_REGION }}
           role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
-          role-session-name: ${{ env.RC_ENV }}-app-deployment
+          role-session-name: ${{ env.RC_ENV }}-backend-app-deployment
           role-duration-seconds: 3600
           role-skip-session-tagging: true
 
       - name: retrieve backend
         env:
           RC_SRC: ${{ env.RC_SRC_PREFIX }}-${{ vars.AWS_ACCOUNT_ID }}
+          VERSION: ${{ needs.validation.outputs.version }}
         run: |
-          [[ $RC_VER =~ ^[0-9]+(\.[0-9]+){2}$ ]] && rc_path="releases/$RC_VER/backend" || rc_path="releases-dev/$RC_VER/backend"
+          [[ $VERSION =~ ^[0-9]+(\.[0-9]+){2}$ ]] && rc_path="releases/$VERSION/backend" || rc_path="releases-dev/$VERSION/backend"
 
           aws s3 cp s3://$RC_SRC/$rc_path/packaged.yml .
           aws s3 cp s3://$RC_SRC/$rc_path/samconfig.yml .
-          echo "[INFO] Application component (BACKEND) with version ${RC_VER} successfully downloaded"
+          echo "[INFO] Application component (BACKEND) with version ${VERSION} successfully downloaded"
       
       - name: get stack name
         id: get-stack
@@ -122,6 +213,8 @@ jobs:
           cmd: yq -r '."${{ env.RC_ENV }}".deploy.parameters.stack_name' samconfig.yml
 
       - name: deploy backend for ${{ env.RC_ENV }}
+        env:
+          VERSION: ${{ needs.validation.outputs.version }}
         run: |
           sam deploy \
             --template-file packaged.yml \
@@ -130,13 +223,15 @@ jobs:
             --region $AWS_REGION \
             --no-confirm-changeset \
             --no-fail-on-empty-changeset
-          echo "[INFO] Application component (BACKEND) with version ${RC_VER} successfully deployed into ${RC_ENV^^}"
+          echo "[INFO] Application component (BACKEND) with version ${VERSION} successfully deployed into ${RC_ENV^^}"
 
   frontend:
     runs-on: ubuntu-latest
     environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment ||
       github.event_name == 'repository_dispatch' && github.event.client_payload.environment }}
-    needs: backend
+    needs: 
+      - validation
+      - backend
 
     steps:
       - name: configure aws credentials
@@ -144,19 +239,20 @@ jobs:
         with:
           aws-region: ${{ env.AWS_REGION }}
           role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
-          role-session-name: ${{ env.RC_ENV }}-app-deployment
+          role-session-name: ${{ env.RC_ENV }}-frontend-app-deployment
           role-duration-seconds: 3600
           role-skip-session-tagging: true
 
       - name: retrieve frontend for ${{ env.RC_ENV }}
         env:
           RC_SRC: ${{ env.RC_SRC_PREFIX }}-${{ vars.AWS_ACCOUNT_ID }}
+          VERSION: ${{ needs.validation.outputs.version }}
         run: |
-          [[ $RC_VER =~ ^[0-9]+(\.[0-9]+){2}$ ]] && rc_path="releases/$RC_VER/frontend/$RC_ENV" || rc_path="releases-dev/$RC_VER/frontend/$RC_ENV"
+          [[ $VERSION =~ ^[0-9]+(\.[0-9]+){2}$ ]] && rc_path="releases/$VERSION/frontend/$RC_ENV" || rc_path="releases-dev/$VERSION/frontend/$RC_ENV"
 
           mkdir build/
           aws s3 cp s3://$RC_SRC/$rc_path/ build/ --recursive
-          echo "[INFO] Application component (FRONTEND) with version ${RC_VER} successfully downloaded for ${RC_ENV^^}"
+          echo "[INFO] Application component (FRONTEND) with version ${VERSION} successfully downloaded for ${RC_ENV^^}"
 
       - name: get frontend bucket name
         id: get-bucket
@@ -174,6 +270,8 @@ jobs:
           echo "[INFO] S3 Bucket for application component (FRONTEND) successfully cleared for ${RC_ENV^^}"
 
       - name: deploy frontend for ${{ env.RC_ENV }}
+        env:
+          VERSION: ${{ needs.validation.outputs.version }}
         run: |
           aws s3 cp build/ ${{ steps.get-bucket.outputs.frontend-bucket-name }} --recursive
-          echo "[INFO] Application component (FRONTEND) with version ${RC_VER} successfully deployed for ${RC_ENV^^}"
+          echo "[INFO] Application component (FRONTEND) with version ${VERSION} successfully deployed for ${RC_ENV^^}"
